version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  assignees:
  - danocmx
  
  groups:
    all-dependencies:
      patterns:
        - "*"
      update-types:
        - "patch"
        - "minor"
