module.exports = {
    "Normal": 0,
    "Genuine": 1,
    "Vintage": 3,
    "rarity3": 4,
    "Unusual": 5,
    "Unique": 6,
    "Community": 7,
    "Valve": 8,
    "Self-Made": 9,
    "Customized": 10,
    "Strange": 11,
    "Completed": 12,
    "Haunted": 13,
    "Collector's": 14,
    "Decorated Weapon": 15,

    '0': 'Normal',
    '1': 'Genuine',
    '3': 'Vintage',
    '4': 'rarity3',
    '5': 'Unusual',
    '6': 'Unique',
    '7': 'Community',
    '8': 'Valve',
    '9': 'Self-Made',
    '10': 'Customized',
    '11': 'Strange',
    '12': 'Completed',
    '13': 'Haunted',
    '14': 'Collector\'s',
    '15': 'Decorated Weapon'
};